// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAutostart():Promise<boolean>;

export function GetConfig():Promise<main.Config>;

export function GetStatus():Promise<main.DaemonStatus>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Logout():Promise<void>;

export function OpenFolder():Promise<void>;

export function OpenWebUI():Promise<void>;

export function PickFolder():Promise<string>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetShareDir(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;
