// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenWebUI() {
  return window['go']['main']['App']['OpenWebUI']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetShareDir(arg1) {
  return window['go']['main']['App']['SetShareDir'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
